name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3']
        rails_version: ['6.1.7.6', '7.0.8', '7.1.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: sul.yaml
        config_data: |
          extends: default
          rules:
            line-length:
              max: 160
